services:
  app:
    container_name: app
    build: .
    command: 'bash -c "diesel setup && cargo watch --exec run"'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/realworld-rust-actix-web
  db:
    container_name: db
    image: "postgres:14.0-alpine"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: realworld-rust-actix-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  .:
